"""empty message

Revision ID: 503ab753bc2f
Revises: a191f77758d1
Create Date: 2019-12-01 19:33:33.067587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503ab753bc2f'
down_revision = 'a191f77758d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat', sa.Column('user_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat', 'user_name')
    # ### end Alembic commands ###
